version: '3'
services:
  master:
    image: bitnami/spark:3.1.2
    container_name: spark-master
    ports:
      - "8081:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=master

  worker1:
    image: bitnami/spark:3.1.2
    container_name: spark-worker1
    links:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=master

  worker2:
    image: bitnami/spark:3.1.2
    container_name: spark-worker2
    links:
      - master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_HOST=master
      
      
      

#services:
#  spark:
#    image: docker.io/bitnami/spark:3.4	spark:2.4.6
#    environment:
#      - SPARK_MODE=master
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#      - SPARK_USER=spark
#    ports:
#      - '8080:8080'
#  spark-worker:
#    image: docker.io/bitnami/spark:3.4
#    environment:
#      - SPARK_MODE=worker
#      - SPARK_MASTER_URL=spark://spark:7077
#      - SPARK_WORKER_MEMORY=1G
#      - SPARK_WORKER_CORES=1
#      - SPARK_RPC_AUTHENTICATION_ENABLED=no
#      - SPARK_RPC_ENCRYPTION_ENABLED=no
#      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
#      - SPARK_SSL_ENABLED=no
#      - SPARK_USER=spark
